FROM tomcat:10.1-jdk17

# Xoá ứng dụng mặc định trong thư mục webapps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy WAR file (giả sử tên là myapp.war) vào Tomcat
COPY LearningPro192_chatBot.war /usr/local/tomcat/webapps/

# Mở port 8080
EXPOSE 8080

# Chạy Tomcat
CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]
